name: Okteto Flask REST API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Run python tests
      run: python3 -m pytest --log-cli-level=INFO
      env:
        COUCHDB_URL: http://couchdb-admin:couchdb-password@database:5984

