name: Okteto Flask REST API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Login to Okteto Cloud
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create staging namespace
      uses: okteto/create-namespace@master
      with:
        namespace: staging-${{ github.event.number }}-vickywane

    - name: Deploy to Staging Flask Application Namespace
      uses: okteto/deploy-stack@master
      with:
        name: staging-${{ github.event.number }}-vickywane
        build: true

    - uses: nev7n/wait_for_response@v1
      with:
        url: https://api-staging-${{ github.event.number }}-vickywane.cloud.okteto.net
        responseCode: 200
        timeout: 4000

    - name: Run API tests agaisnt Staging Namespace
      run: pytest
      env:
        STAGING_COUCHDB_URL: https://api-staging-${{ github.event.number }}-vickywane.cloud.okteto.net

    - name: Build and deploy application container to Okteto Flask Namespace
      if: ${{ github.event_name == 'push' }}
      uses: okteto/deploy-stack@master
      with:
        name: okteto-flask-app
        build: true