name: Okteto Flask REST API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Login to Okteto Cloud
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate application namespace
      uses: okteto/namespace@master
      with:
        namespace: vickywane

    - name: Deploy to test Staging Okteto Namespace
      uses: okteto/deploy-stack@master
      with:
        namespace: pr-staging-${{ github.event.number }}-namespace
        build: true

    - name: Run API tests agaisnt Staging Namespace
      run: pytest
      env:
        STAGING_COUCHDB_URL: https://web-pr-${{ github.event.number }}-namespace.cloud.okteto.net

    - name: Build and deploy application container to Okteto Flask Namespace
      if: ${{ github.event_name == 'push' }}
      uses: okteto/deploy-stack@master
      with:
        name: okteto-flask-app
        build: true

    - name: Test endpoints agaisnt the test CouchDB instance
      run: pytest
      env:
        COUCHDB_URL: http://127.0.0.1:5984
